### ISSUE TITLE
the web is down

### ISSUE THREAD

**Issue by henson** [sanddudu/LastDay#1]
The address _http://nichijou.in/LastDay/yyyy/mm/dd.json_  can not be visited. The default branch
_gh-pages_ is on failure: Page build failed.

**Comment by sanddudu** [comment]
Thank you for your feedback. We are investigating the problem.

**Comment by henson** [comment]
failed again

**Comment by sanddudu** [comment]
@henson Things became more difficult that what we thought.
In normal cases, Github will send us an email to address the reason for building fail. But this time, there was nothing. I am sorry to say, we need extra time to deal with the problem.

**Comment by henson** [comment]
maybe too many files, github could not build automaticly

**Comment by orzFly** [comment]
Hate to say, but we are now having 1,933 files and directories. However, I cannot find any official pages about this limitation in GitHub Pages.

**Comment by henson** [comment]
GitHub Pages have no limits of files, but build them cost too much time, beyond the timeout set, I think.

**Comment by sanddudu** [comment]
@henson There is also no any official pages for this limits. I have contacted the support for help.

**Comment by henson** [comment]
thanks

**Comment by sanddudu** [comment]
Github support claimed that Github Pages has a build timeout limit. All data is accessible right now. Thank you for your patient.

**Comment by henson** [comment]
2018/03/11.json&2018/03/12.json are unfound
