### ISSUE TITLE
数据更新问题（2023.05.25）

### ISSUE THREAD

**Issue by henson** [sanddudu/LastDay#2]
能继续更新么

**Comment by sanddudu** [comment]
感谢您的提醒，目前数据更新已恢复

**Comment by henson** [comment]
不再更新了？数据停在2023年5月25日了

**Comment by sanddudu** [comment]
最近 nextday 服务器出现了问题，他们刚刚上架了新的应用，但是目前为止测试使用新的应用也无法连接到他们的数据服务器，所以内容更新的问题可能需要等下一次机器人能够正常连接才可以。
更新机器人由我的朋友负责维护，如果这次故障修复后他们选择了新的内容分发方式，那么这个仓库可能更新就到此为止，希望您能理解。

**Comment by sanddudu** [comment]
已经调查清楚，导致更新失败的主要原因是 Nextday 应用中自签发的证书于 21 日过期。已经从新版本应用中提取了新的证书，目前更新已经恢复。
